Update to the MTU test readme to cover for Tunnel interfaces. (#3401)
* Update to the MTU test readme to cover for Tunnel interfaces.

- Separate the test to 2 sub tests
- While the original test covered MTU configuration on physical/Bundle  interfaces only, added subtest covers for Tunnel interface MTU configuration and corresponding emphasis on zero fragmentation plus packet drops.

Updated write-up also covers for missed config and state paths.

* Update README.md

Added additional clarity on the tunnel interface MTU config  that it isn't mandatory for the NOS to allow for MTU config on tunnel interfaces. Expectation is for the tunnel interface to respect the MTU configured on the underlying physical or bundle interface acting as an egress point.

* Update README.md

updated the following bullet for MTU-1.3.2

Ensure MTU configured on this tunnel interface is in context to the MTU on the egress physical/bundle interface. It is acceptable if the implementation doesn't support explicit MTU config on tunnel interfaces. Idea is for the tunnel interface to respect the egress physical/bundle interface MTU config.

* Update README.md

* Update README.md

Corrected Yaml error

* Update README.md

* Update README.md

* Update README.md

Updated paths that were incorrectly defined.

* Update README.md

Corrected the OC path   /interfaces/interface/tunnel/config/dst:

It was originally   /interfaces/interface/tunnel/config/dest:

* Adding canonical OC to config path

Changing the config to the approach suggested in https://github.com/openconfig/featureprofiles/pull/3336

* Update README.md

Trying to correct the error

Run go install ./tools/validate_readme_spec
########## READMEs in changed directories to be validated (including ones to be exempted):
feature/mtu/largeippacket/otg_tests/large_ip_packet_transmission/README.md
########## Validating READMEs in changed directories:
I0830 17:54:13.842665    4350 validate_readme_spec.go:149] Validating "feature/mtu/largeippacket/otg_tests/large_ip_packet_transmission/README.md"
E0830 17:54:13.843301    4350 validate_readme_spec.go:156] file feature/mtu/largeippacket/otg_tests/large_ip_packet_transmission/README.md: mdocspec: error parsing YAML: yaml: unmarshal errors:
  line 4: cannot unmarshal !!seq into map[string]interface {}
F0830 17:54:13.843594    4350 validate_readme_spec.go:178] The following files have errors:
feature/mtu/largeippacket/otg_tests/large_ip_packet_transmission/README.md
Error: Process completed with exit code 1.

* Update README.md

* Update README.md

Moved the canonical config to the Test procedure area. Also, restored the section under ## OpenConfig Path and RPC Coverage to how it was before.